# Site
title: Porcupine Improv
tagline: 'Play for Everyone'
description: >- # this means to ignore newlines until "baseurl:"
  Let's learn how to play together again.
url: "https://tullymcloughlin.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/improv" # the subpath of your site, e.g. /blog

# Me
email: tully.mcloughlin@gmail.com
github_username:  tullymcloughlin

# Build settings
remote_theme: poole/hyde
plugins:
  - jekyll-feed
  - jekyll-remote-theme

#Dependencies



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
