remote_theme:  ritijjain/pudhina-fresh

title: Tully Improv # Shown in header on pages with full_logo: true
short_logo: T. # Shown in header on all pages by default unless full_logo: true is set
description: > # The description for your site
  A minimal yet feature-rich Jekyll theme made for personal websites and blogs.
url: "https://ritijjain.github.io/pudhina-fresh" # The base hostname & protocol for your site

author:
  name: Tully McLoughlin
  github: tullymcloughlin/improv # GitHub username, used for GitHub icon on the top right
  linkedin: tully-mcloughlin-13a68710 # Your LinkedIn profile url name, used for LinkedIn icon on the top right
  email: tully.mcloughlin@gmail.com # Used for email icon on the top right

disqus_name: # Setting this will turn on Disqus comments
g_track_id: # Google Analytics tracking ID (e.g. UA-000000-2), setting this will turn on Google Analytics
rss: false # RSS feed icon on or off
